apiVersion: v1
kind: Service
metadata:
  name: note-service
  labels:
    app: note-service
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: note-service
---  
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: note-service-v1
spec:
  replicas: 1  
  template:
    metadata:
      labels:
        app: note-service
        version: v1
    spec:
      containers:
        - name: app
          image: gcr.io/mtech-wms-backstage-poc/notes-service:0.3
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: 127.0.0.1:3306
            - name: DB_URL
              value: jdbc:mysql://127.0.0.1/backstage?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials-backstage-dev
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials-backstage-dev
                  key: password
            - name: DATABASE
              value: backstage
            - name: KAFKA_BOOTSTRAP
              value: 10.254.128.13:9092
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=mtech-wms-backstage-poc:us-east4:backstage-db-1=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      # [END volumes]
---
